### PR TITLE
Update to more recent version of Atom !

### PR DESCRIPTION
**Pull request by ghivert**
Hi !

Just to improve the soft ! (Non working in the repos for me...)

### CODE REVIEW

**Comment by jenius** [comment]
So it looks like you removed the "toggle" capability here? The hotkey just hits "fold"...

**Comment by ghivert** [comment]
I just renamed Toggle to Fold all and Unfold All as it seemed me more explicit. (And it allow to fold or unfold as needed.) :) Added a shortcut if needed, and fixed a mistake.

**Comment by jenius** [comment]
This is looking much better now, thanks for taking the time to revise and review! Could you possibly squash the commits before merge?

**Comment by ghivert** [comment]
Yup ! Much better now ! It's a pleasure to contribute ! :)
(I realized really late that toggle folded and unfolded in same time...)

**Comment by ghivert** [comment]
Yup. I was trying to reduce repetition, but CoffeeScript is not really my favorite language. So sometimes, repetition is more easy ! :) I'm thinking about it.
Wait for a new commit in the future, because the check of comment could be simpler with isBufferRowCommented. :)

**Comment by jenius** [comment]
Sounds good -- just ping me here when you have an update! Thanks for your hard work on solving this issue :grinning:

**Comment by ghivert** [comment]
Ok, work done ! Merge if you like it ! (I think we can't really get a cleaner solution, no ?)

**Comment by jenius** [comment]
Awesome, this looks fantastic. One last nitpick, can you squash these two commits together so they come in as one commit? That way it will appear more cleanly in the history :grinning: 

Looks ready for merge after that!

**Comment by ghivert** [comment]
And it's done ! :) A little bit long to merge two commits, but finally it's here !

**Comment by jenius** [comment]
Awesome, this looks so great. Thanks @ghivert for a lot of hard work on this. I'll ship it out now!

**Pull request merged**
