### PR TITLE
use activationCommands

### PR DESCRIPTION
**Pull request by t9md**
use `activationCommands` instead of  `activationEvents`.

### CODE REVIEW

**Comment by jenius** [comment]
Could you explain a little more of the reasoning behind this, just out of curiosity?

**Comment by t9md** [comment]
Just followed deprecate-cop's warning messages.

Here is where activate `activationEvents` is treated as deprecatedAPI.

https://github.com/atom/atom/blob/master/src/package.coffee#L495-L504

I don't know why and background, but it seem many package developer following this way.

Thanks.

**Comment by t9md** [comment]
this PR is where documentation was updated.

https://github.com/atom/docs/pull/15

**Comment by jenius** [comment]
Great, thanks! Just wanted to have some sort of explanation here for the record :grinning:

**Comment by t9md** [comment]
Thanks!

**Comment by t9md** [comment]
Deprecated Atom APIs will be removed June 1st.
atom/atom#6867

Please release package beforehand.
This have been already fixed by this PR.
I'm using this plugin.

**Comment by jenius** [comment]
Hi @t9md -- sorry for the delay I'm currently traveling and my connectivity is on and off. I'll have this taken care of today.

**Comment by jenius** [comment]
Published as `fold-comments@v0.4.0`

**Pull request merged**
